# hash-identificacao: ed9d0beb972d4ee73eb40c15bcc695525d38b4ba21afe6eb7adbff2bcee11e97

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true
# Formata o JSON das responstas com indetação
